name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        run: |
          COMMIT_MESSAGES=$(git log origin/main..HEAD --pretty=format:"%s")
          echo "$COMMIT_MESSAGES"
        id: commit_messages

      - name: Validate commit messages
        run: |
          PREFIXES="^(fix|feat|docs|ci|chore):"
          while IFS= read -r line; do
            if [[ ! $line =~ $PREFIXES ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done <<< "${{ steps.commit_messages.outputs.COMMIT_MESSAGES }}"
