name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages
        id: get_commit_messages
        run: |
          COMMIT_MESSAGES=$(git log origin/main..HEAD --pretty=format:"%s")
          echo "::set-output name=messages::$COMMIT_MESSAGES"

      - name: Validate commit messages
        if: ${{ steps.get_commit_messages.outputs.messages != '' }}
        run: |
          PREFIXES="^(fix|feat|docs|ci|chore):"
          echo "${{ steps.get_commit_messages.outputs.messages }}" | while IFS= read -r line; do
            if [[ ! $line =~ $PREFIXES ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done
